Sanity test:
This script performs end to end test on haploclique project for dataset simulated from HIV-1. First, two new haplotypes are generated by 0.1 mean number of nc substitutions. In the next step, the paired-end reads are generated with coverage 50. 
  $ haploclique_output_path=${HOME}/${CIRCLE_PROJECT_REPONAME}/test/data/simulation
  $ cd $haploclique_output_path 
Run haploclique
  $ haploclique_exe_path=../../../build/src
  $ /home/ubuntu/haploclique/build/src/haploclique reads_HIV-1_50_01.bam > /dev/null;
Compare the new output file with the original output file. Test will pass if they are same. 
  $ diff quasispecies.fasta.fasta quasispecies_HIV-1_50_circleci.fasta.fasta > out.txt;
  $ if [ -s out.txt ]; then echo "Different"; else echo "Same"; fi;
  Same
